// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akeicrdupksmfegurbgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZWljcmR1cGtzbWZlZ3VyYmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTUxMTEsImV4cCI6MjA2MTQ5MTExMX0.uzKr7W-g3JoBJERx_F5GeTTsR8K936l493EP5zgzd8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);