// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvttiucbutigkqzdpblq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2dHRpdWNidXRpZ2txemRwYmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTAxMDIsImV4cCI6MjA2NDAyNjEwMn0.-33RM0DSJzox3XfNa1yIhupgpRw5fuYJUHiOjp3bIbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);